### ISSUE TITLE
Задачки B

### ISSUE THREAD

**Issue by Tratut** [Tratut/WaspTasks#6]
Сори что тэгаю обоих(пришлось так сделать тк не написано кому сдавать)
@vdetstvepil @TimohaTB

**Comment by vdetstvepil** [comment]
Репозиторий пуст

**Comment by vdetstvepil** [comment]
А, нет, не пуст. Но тесты не проходит

**Comment by Tratut** [comment]
level B у меня не проходит только 4 задача, остальные должны быть ок

**Comment by vdetstvepil** [comment]
Скриншот, пожалуйста, со средой

**Comment by vdetstvepil** [comment]
Прикладываю логи со своей стороны - тесты не проходит
![image](https://user-images.githubusercontent.com/53276813/142739262-ce58acc3-11f3-422e-96d2-fc30a3d808d0.png)

**Comment by Tratut** [comment]
![Снимок](https://user-images.githubusercontent.com/64106392/142739330-6030e577-cfd2-41d0-8f08-5b64b47c4dd8.PNG)

**Comment by Tratut** [comment]
В самих тестах были ошибки?(я юзаю те которым ≈ 2-3 дня после выкладывания этой домашки)

**Comment by vdetstvepil** [comment]
В тестах нет ошибок

**Comment by vdetstvepil** [comment]
Лаааадно, поверю на слово, закрою глаза на свои логи и выставлю 2 стингера с гигантской натяжкой. Принято.
